# Generated by Django 3.2 on 2021-04-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='date',
        ),
        migrations.AddField(
            model_name='tweet',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=600),
        ),
        migrations.DeleteModel(
            name='Dag',
        ),
    ]
