# Generated by Django 3.2 on 2021-04-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_alter_tweet_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created']},
        ),
    ]
