# Generated by Django 3.2 on 2021-04-23 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0007_auto_20210423_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollows',
            options={},
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='follower',
        ),
        migrations.AlterField(
            model_name='userfollows',
            name='follows',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
